export const bgColor = '#fffff0'
export const mainTextColor = '#555'
export const tmdbPrimaryColor = '#01d277'
export const ticketMargin = '.25em'
export const ticketFonts = 'font-family: "Bodoni 72", serif'